Fix compiler error.
internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1740
error: explicit capture matches default.
Due to capture Xsize by reference in test file by lambda function. I dont know why it is not accepted.
Anyway, capture by value works fine.